/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/ship_hallway-edited.glb --transform --types 
Files: public/ship_hallway-edited.glb [2.9MB] > C:\Users\akmal\OneDrive\Documents\project\sorakee-portfolio\ship_hallway-edited-transformed.glb [130.28KB] (96%)
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    highpolywall11_Wall_Black_0: THREE.Mesh
    highpolywall11_Wall_blue_0: THREE.Mesh
    highpolywall11_Glass_0: THREE.Mesh
    highpolywall11_Vent_light_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
}

interface SpaceshipProps {
  props?: JSX.IntrinsicElements['group'];
  onLoad: () => void;
}

const Spaceship: React.FC<SpaceshipProps> = ({ props, onLoad }) => {
  const gltf  = useGLTF('/ship_hallway-edited-transformed.glb') as GLTFResult;
  const { nodes, materials } = gltf;

  useEffect(() => {
    if (gltf) {
      onLoad();
    }
  }, [gltf, onLoad]);
  
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={5} decay={1} color='#65bcfc' position={[0, 3.459, -2.304]} />
      <pointLight intensity={5} decay={1} color='#65bcfc' position={[0, 3.367, -7.861]} />
      {/* <pointLight intensity={5} decay={1} position={[0, 3.413, -13.467]} /> */}
      <pointLight intensity={5} decay={1} color='#65bcfc' position={[0, 3.12, 2.95]} />
      <mesh geometry={nodes.highpolywall11_Wall_Black_0.geometry} material={materials.PaletteMaterial001} position={[-20.053, 0, 8.556]} />
      <mesh geometry={nodes.highpolywall11_Wall_blue_0.geometry} material={materials.PaletteMaterial002} position={[-20.053, 0, 8.556]} />
      <mesh geometry={nodes.highpolywall11_Glass_0.geometry} material={materials.PaletteMaterial003} position={[-20.053, 0, 8.556]} />
      <mesh geometry={nodes.highpolywall11_Vent_light_0.geometry} material={materials.PaletteMaterial004} position={[-20.053, 0, 8.556]} />
    </group>
  )
}

export default Spaceship;

useGLTF.preload('/ship_hallway-edited-transformed.glb')
