/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/space_ship_hallway.glb --types --transform 
Files: public/space_ship_hallway.glb [2.9MB] > C:\Users\akmal\OneDrive\Documents\project\sorakee-portfolio\space_ship_hallway-transformed.glb [129.49KB] (96%)
Author: yeeyeeman (https://sketchfab.com/yeeyeeman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-ship-hallway-e97dce00ae5549a8a3795e06bc2cfc96
Title: Space Ship Hallway
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    highpolywall11_Wall_Black_0: THREE.Mesh
    highpolywall11_Wall_blue_0: THREE.Mesh
    highpolywall11_Glass_0: THREE.Mesh
    highpolywall11_Vent_light_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
}

function Spaceship(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/space_ship_hallway-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.highpolywall11_Wall_Black_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.highpolywall11_Wall_blue_0.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.highpolywall11_Glass_0.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.highpolywall11_Vent_light_0.geometry} material={materials.PaletteMaterial004} />
    </group>
  )
}

export default Spaceship;

useGLTF.preload('/space_ship_hallway-transformed.glb')
